server:
  port: 8081

liquibase:
  enabled: true
  drop-first: false

logging:
  level:
    com.gpfs: DEBUG
  

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpfs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    connection-test-query: SELECT 1
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 15000
    min-evictable-idle-time-millis: 60000
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false